spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project3?characterEncoding=utf8
    username: root
    password: 123456

server:
  port: 8080
  servlet:
    context-path: /admin

  #json日期格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#debug: true
#pageHelper配置，分页工具

#pagehelper:
#            helperDialect: mysql
#            reasonable: true
#            supportMethodsArguments: true
#            params: count=countSql
