server:
  port: 8081
  servlet:
    context-path: /
<<<<<<< HEAD
=======
  port: 8080
>>>>>>> f2e7cee981cfcbda2298b1a4a3ce96bae5f7e516

spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/cskaoyanmall?characterEncoding=utf-8&useSSL=false

admin:
  login:
    errmsg: "成功"
    errno: 0
    info:
      avatar: "https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif"
      name: "admin123"
      perms: ["*"]
      roles: ["超级管理员"]
=======
    url: jdbc:mysql://localhost:3306/j14_project_mall?characterEncoding=utf8
>>>>>>> f2e7cee981cfcbda2298b1a4a3ce96bae5f7e516
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


  #json日期格式处理
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
myoss:
  bucket: wpm
  endpoint: oss-cn-shenzhen.aliyuncs.com
  access-key: LTAIZZ8enay6EMyn
  secret: 1sC6XmkJdusTmhNyox5pgDYrAd9aIM

#debug: true
#pageHelper配置，分页工具

#pagehelper:
#            helperDialect: mysql
#            reasonable: true
#            supportMethodsArguments: true
#            params: count=countSql

